### ISSUE TITLE
Executable does not work: ModuleNotFoundError: No module named 'text_detection'

### ISSUE THREAD

**Issue by guysoft** [danwald/pytextractor#2]
Steps to reproduce:
1. Ran ``sudo pip3 install pytextractor``

2. got this output:
```
$ /usr/local/bin/text_detector --help
Traceback (most recent call last):
  File "/usr/local/bin/text_detector", line 6, in <module>
    from text_detection import text_detector
ModuleNotFoundError: No module named 'text_detection'

```

**Comment by danwald** [comment]
This should be fixed as of [v0.5](https://github.com/danwald/pytextractor/releases/tag/v0.5). 
Upgrade the pip package and it should work
Thanks for your interest. 
Cheers
