### ISSUE TITLE
Problem with recognition engine

### ISSUE THREAD

**Issue by jdavidd** [danwald/pytextractor#6]
Hello I try to use this system but doesnt recognize well the words. It finds every text box but the recognition is bad. Like
['\x0c', '\x0c', '\x0c', '\x0c', '\x0c', '\x0c', '\x0c', ' \n\n \n\nHOTELS\n\n \n\n \n\x0c', '"Tata\n\n \n\x0c', '\x0c']P

**Comment by danwald** [comment]
You will have to tweak the parameters so it will work for what you have.

It seems you're getting too much data so try increasing the confidence
perhaps.

Good luck and let me know if that worked or not for you

**Comment by danwald** [comment]
just upgraded the libs... closing this for now
