### ISSUE TITLE
Pytextractor : Error OpenCV(4.4.0) (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::dnn4_v20200609::DataLayer::getMemoryShapes'

### ISSUE THREAD

**Issue by BS-Keerthana** [danwald/pytextractor#9]
Hi, 

While trying to use pytextractor to detect text from images, am getting below error. Please suggest. 

**Package Version** 
opencv-python==4.4.0.46
tesseract v5.0.0.20211201

**Code** :
from pytextractor.pytextractor import PyTextractor

extractor = PyTextractor()
detected = extractor.get_image_text(imagepath, number=True)

**Error**:

[ERROR:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nxx381if\opencv\modules\dnn\src\dnn.cpp (3444) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively OPENCV/DNN: []:(_input): getMemoryShapes() throws exception. inputs=1 outputs=0/0 blobs=0
[ERROR:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nxx381if\opencv\modules\dnn\src\dnn.cpp (3447) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 3 320 320 ]
[ERROR:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nxx381if\opencv\modules\dnn\src\dnn.cpp (3457) cv::dnn::dnn4_v20200609::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nxx381if\opencv\modules\dnn\src\dnn.cpp:784: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::dnn4_v20200609::DataLayer::getMemoryShapes'

Error OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-nxx381if\opencv\modules\dnn\src\dnn.cpp:784: error: (-215:Assertion failed) inputs.size() == requiredOutputs in function 'cv::dnn::dnn4_v20200609::DataLayer::getMemoryShapes'

**Comment by danwald** [comment]
can you please provide me with the image you are using so I can help debug?
- danny

**Comment by danwald** [comment]
just upgraded the libs
hope this fixes your issue ...
reopen if it doesn't 
cheers
